### ISSUE TITLE
New server in Amsterdam

### ISSUE THREAD

**Issue by ooonea** [jedisct1/dnscrypt-server-docker#14]
Hi, can you add my new server to the list of public servers?
The name of the server 'kenshiro' maintained by 'lucenera'.

Stamp for dnscrypt-proxy 2.x:
  sdns://AQcAAAAAAAAAETk1LjE3OS4xODQuNDI6NDQzIEwMaXrAHpHJshPm0pdTOBgIuscld9eWasZAuEIoQzeRHzIuZG5zY3J5cHQtY2VydC5hbS5rZW5zaGlyby5uZXQ

Parameters for dnscrypt-proxy 1.x:
  dnscrypt-proxy --provider-key=4C0C:697A:C01E:91C9:B213:E6D2:9753:3818:08BA:C725:77D7:966A:C640:B842:2843:3791
                 --resolver-address=95.179.184.42:443
                 --provider-name=2.dnscrypt-cert.am.kenshiro.net
Keys are stored in public.key & secret.key.

It already works, I'm using it. I followed the other guide, the one for Vultr.

**Comment by jedisct1** [comment]
`kenshiro` has been added!

Thanks!
