### ISSUE TITLE
New server in Italy

### ISSUE THREAD

**Issue by ooonea** [jedisct1/dnscrypt-server-docker#15]
Using the docker container, I activated my third and last server. Name 'edociccio' maintained by 'lucenera'.
Please add it to the list of public servers.

Provider name: [2.dnscrypt-cert.it.edociccio.com]
Generate provider key pair... ok.
Stamp for dnscrypt-proxy 2.x:
  sdns://AQcAAAAAAAAAEDgwLjIxMS44NS41MTo0NDMgVlvIU4uMbrMcCK-Z2BFcNuOY7bA-foVglnx9mfukn0AgMi5kbnNjcnlwdC1jZXJ0Lml0LmVkb2NpY2Npby5jb20

Parameters for dnscrypt-proxy 1.x:
  dnscrypt-proxy --provider-key=565B:C853:8B8C:6EB3:1C08:AF99:D811:5C36:E398:EDB0:3E7E:8560:967C:7D99:FBA4:9F40
                 --resolver-address=80.211.85.51:443
                 --provider-name=2.dnscrypt-cert.it.edociccio.com
Keys are stored in public.key & secret.key.

**Comment by jedisct1** [comment]
Added!

Welcome to edociccio!
