### ISSUE TITLE
Change servers

### ISSUE THREAD

**Issue by ooonea** [jedisct1/dnscrypt-server-docker#16]
Hello, I'm sorry if I ask you to change the list of public servers again. I had to move all the servers on one service for practical reasons.
So I ask you the courtesy to replace suami and kenshiro with the new parameters.

suami:
Stamp for dnscrypt-proxy 2.x:
  sdns://AQcAAAAAAAAAEjE5NC4xODIuNjYuMTM1OjQ0MyBs6XoJJGAtOCbPFpgQhF1edKnCR7BGqXoThb940iaawxwyLmRuc2NyeXB0LWNlcnQuY3ouc3VhbWkuY29t

Parameters for dnscrypt-proxy 1.x:
  dnscrypt-proxy --provider-key=6CE9:7A09:2460:2D38:26CF:1698:1084:5D5E:74A9:C247:B046:A97A:1385:BF78:D226:9AC3
                 --resolver-address=194.182.66.135:443
                 --provider-name=2.dnscrypt-cert.cz.suami.com
Keys are stored in public.key & secret.key.

kenshiro:
Stamp for dnscrypt-proxy 2.x:
  sdns://AQcAAAAAAAAADzg2LjEwNS41MS43OjQ0MyBtR6d6WOPiChlf4G7hoeeXt_lqQaMnFje9HVyedB8vjB8yLmRuc2NyeXB0LWNlcnQuZGUua2Vuc2hpcm8uY29t

Parameters for dnscrypt-proxy 1.x:
  dnscrypt-proxy --provider-key=6D47:A77A:58E3:E20A:195F:E06E:E1A1:E797:B7F9:6A41:A327:1637:BD1D:5C9E:741F:2F8C
                 --resolver-address=86.105.51.7:443
                 --provider-name=2.dnscrypt-cert.de.kenshiro.com
Keys are stored in public.key & secret.key.

Thank you so much for your understanding.

**Comment by ooonea** [comment]
The localities have also changed: suami is in the Czech Republic and kenshiro in Germany.

**Comment by jedisct1** [comment]
No problem! The changes have been made.
