### ISSUE TITLE
New server

### ISSUE THREAD

**Issue by ooonea** [jedisct1/dnscrypt-server-docker#18]
Here is a new server:
name: denise in the Czech Republic.

Stamp for dnscrypt-proxy 2.x:
  sdns://AQcAAAAAAAAAETgwLjIxMS4yNDQuNTI6NDQzIABIuBTlNsk95Z8pu3jdALv_P-xLFK03X5GMFHfrpNhtHTIuZG5zY3J5cHQtY2VydC5wbC5kZW5pc2UuY29t

Parameters for dnscrypt-proxy 1.x:
  dnscrypt-proxy --provider-key=0048:B814:E536:C93D:E59F:29BB:78DD:00BB:FF3F:EC4B:14AD:375F:918C:1477:EBA4:D86D
                 --resolver-address=80.211.244.52:443
                 --provider-name=2.dnscrypt-cert.pl.denise.com
Keys are stored in public.key & secret.key.

**Comment by jedisct1** [comment]
Wow, nice!

Added!

**Comment by jedisct1** [comment]
By the way, only the DNS stamp is required.

Informations for dnscrypt-proxy 1.x are already present in the stamp.

**Comment by ooonea** [comment]
Ok, thnak you so much. I'll keep it in account for the next server.
