### ISSUE TITLE
New server in Italy 2

### ISSUE THREAD

**Issue by ooonea** [jedisct1/dnscrypt-server-docker#19]
Hi, now it's like a drug. I think this is the latest.
lucenera by lucenera
sdns: // AQcAAAAAAAAAETIxMi4yMzcuMzguMTU6NDQzIJA89roKfn8cBGMnIrfpWVdHmtl5b8IbtSxx2gamVIS5HzIuZG5zY3J5cHQtY2VydC5pdC5sdWNlbmVyYS5jb20

**Comment by jedisct1** [comment]
You never stop!

Thanks for that new one!

**Comment by ooonea** [comment]
Thanks to you ;)

**Comment by jedisct1** [comment]
Added!

Welcome to Lucenera!

I like the names of your servers :)
