### ISSUE TITLE
ED25519 & ED448

### ISSUE THREAD

**Issue by mibere** [jedisct1/dnscrypt-server-docker#20]
Is it correct that by using this Docker image in combination with dnscrypt-proxy 2.0.19 the test for _ED25519_ and _ED448_ reports

> This DS and signing algorithm combination are not validated by your resolver(s)

on https://rootcanary.org/test.html?

**Comment by jedisct1** [comment]
Unbound supports these, but maybe it didn't detect them being present in LibreSSL.

The LibreSSL version currently shipped with Alpine Linux is also quite old.

I'm going to switch to OpenSSL.

That being said, not supporting EdDSA for DNSSEC signatures is not a big deal since virtually no servers use them.

**Comment by jedisct1** [comment]
Done :)

**Comment by mibere** [comment]
My [dnscrypt.me](https://dnscrypt.me/) is running with the changes (OpenSSL, libsodium-stable) now. ED25519 & ED448 are supported:

![Bildschirmfoto 2019-03-11 um 18 28 36](https://user-images.githubusercontent.com/17352825/54144223-8d838500-442b-11e9-8f35-71a4ff55a5b6.png)

Just for information: with LibreSSL there was support for GOST / ECC-GOST. OpenSSL doesn't include GOST anymore (see [changelog](https://www.openssl.org/news/cl110.txt)):

>   *) The GOST engine was out of date and therefore it has been removed. An up
>      to date GOST engine is now being maintained in an external repository.
>      See: https://wiki.openssl.org/index.php/Binaries. Libssl still retains
>      support for GOST ciphersuites (these are only activated if a GOST engine
>      is present).

**Comment by jedisct1** [comment]
Thanks for the report!

We can probably live without GOST.
