### ISSUE TITLE
Changes to the dnscrypt-server components

### ISSUE THREAD

**Issue by ooonea** [jedisct1/dnscrypt-server-docker#21]
Being subscribed to the project mailing list I read that you switched to OprnSSL. Do I have to follow this guide to update my servers? https://github.com/jedisct1/dnscrypt-proxy/wiki/Manually-updating-your-DNSCrypt-server

**Comment by jedisct1** [comment]
You can.

But honestly, there is absolutely no urgency to do it. The current version you are running is fine.
So only do it if you are bored :)

**Comment by ooonea** [comment]
Thank you so much for your answer. At the moment I activated watchtower. I tried on one of the servers to upgrade according to the aforementioned guide. But I had a strange log about certain limits and unbound. But I do not understand anything. I had created a snapshot and I came back. If you're interested, I'll try again and send you the log.

**Comment by jedisct1** [comment]
I'd be definitely interested in these logs if you have time.

**Comment by ooonea** [comment]
Ok. Tomorrow afternoon I redo everything. Now sleep, then work, then family and then server. Thanks for your patience. I would like to understand something too.

**Comment by ooonea** [comment]
I am attaching the logs of one of the servers. The logs file comes from the 'docker logs dnscrypt-server' command. The unbound_warning file is an extract of the log that reports the unbound warnings I was telling you about. The file docker_inspect finally comes from the command 'docker inspect dnscrypt-server' from which I understand that nothing has been updated, because I always read libressl. Let me know.
PS: The three files are in the log.zip, plus I added a screenshot of the https://rootcanary.org/test.html of my servers. Worse than before.


[log.zip](https://github.com/jedisct1/dnscrypt-server-docker/files/2953544/log.zip)
![edociccio_server](https://user-images.githubusercontent.com/35407790/54145002-4c8c7000-442d-11e9-97ff-23d529b35226.png)

**Comment by jedisct1** [comment]
Weird, it definitely looks like you are not running the current image.

**Comment by ooonea** [comment]
How can I update? I followed the guide on Github to manually update the container. Then I installed and activated watchtower. But the result is the same. How can I do? Even if I uninstall and install again, nothing changes. I follow the guide for Scaleway.

**Comment by jedisct1** [comment]
Looks like the Docker Hub didn't properly build the new version.

I triggered a new build. Give it a couple minutes :)

**Comment by ooonea** [comment]
Ok. Thank you so much Frank. I'll try soon and I'll let you know. But those unbound notices? What's up?

**Comment by jedisct1** [comment]
I think these are limits enforced by Kubernetes or whatever runs your containers.

**Comment by ooonea** [comment]
I use Docker.

**Comment by jedisct1** [comment]
Maybe this could help? https://mtyurt.net/post/docker-how-to-increase-number-of-open-files-limit.html

**Comment by ooonea** [comment]
Now I try everything and let you know. You are very kind.

**Comment by jedisct1** [comment]
Looks like the new image is on the Docker hub!

**Comment by ooonea** [comment]
In fact I had reproached, but still nothing. Now I have updated the first server manually and the others have updated with watchtower, but rightfully I have to manually reset the keys. So it's automatic in half. The test, however, does not change and I seem to be different from the one attached by the user 'mibere'.
![edociccio_server](https://user-images.githubusercontent.com/35407790/54148527-9f1d5a80-4434-11e9-82b9-093485890d88.png)

**Comment by mibere** [comment]
@lucenera did you try a browser reload of the page **+** "Re-run test"? The test sometimes behave a bit strange.

**Comment by ooonea** [comment]
@mibere Yes thanks. It was just a matter of browser cache. I tried in an anonymous browsing window and the test matches yours. By any chance do you know how to use the --ulimit in docker option?

**Comment by mibere** [comment]
I didn't change anything regarding _ulimit_ in Docker - just on the host.

After 

`docker exec -it dnscrypt-server /bin/bash`

followed by a

`ulimit -n`

the output on my system is "1048576".

And `ulimit -n` on my host outputs "16384" (default was "1024").

**Comment by ooonea** [comment]
My limit in docker (unlimit -n) is 1024. How do I fix it?

**Comment by mibere** [comment]
The link posted by Frank should help, see [above](https://github.com/jedisct1/dnscrypt-server-docker/issues/21#issuecomment-471654629).

_I'm confused why my default in the Docker container is 1048576._

**Comment by ooonea** [comment]
@mibere In fact, your default limit is very high. I was able to use the instructions on the page that Frank suggested to me and now I modified the guide to create the server in 10 minutes. So others will not have my same problem.

**Comment by jedisct1** [comment]
Thanks a lot for having updated the instructions!

**Comment by jedisct1** [comment]
(my defaults are very high as well, same as @mibere ... Not sure why ... I use stock Ubuntu).

**Comment by ooonea** [comment]
I do what I can and now I put something more in the guide to help people like me who do not understand too much. Increasing the limit to 90000 already I do not receive any more errors. I also use Ubuntu stock and I do not know why your limit is so high by default. Will it be the Ubuntu version? I use Ubuntu Server 18.04.2.

**Comment by ooonea** [comment]
I would also advise against watchtower for this container for the key problem. But maybe it's me that I do not know how to automatically restore them to the update. How do I know when your container is updated in Docker Hub? Then update it manually.

**Comment by mibere** [comment]
After I connect into the container

`cat /etc/alpine-release`

=> 3.9.2

**Comment by ooonea** [comment]
Host
Distributor ID: Ubuntu
Description: Ubuntu 18.04.2 LTS
Release: 18.04
Codename: bionic

Docker
Docker version 18.06.1-ce, build e68fc7a

Container' alpine
cat /etc/alpine-release
3.9.2

**Comment by mibere** [comment]
Ah, maybe because of this:

On my host (Debian 9.8)

`grep -i limit  /etc/init/docker.conf`

=> _limit nofile 524288 1048576_

I definitively didn't modify that file.

**Comment by ooonea** [comment]
Probably Ubuntu is much more conservative. Ubuntu itself is set at 1024.
