### ISSUE TITLE
Re-using existing volume (keys) during update?

### ISSUE THREAD

**Issue by mibere** [jedisct1/dnscrypt-server-docker#23]
The container places keys in a volume, see [Dockerfile](https://github.com/jedisct1/dnscrypt-server-docker/blob/master/Dockerfile#L83).

Regarding [this tutorial](https://github.com/jedisct1/dnscrypt-proxy/wiki/Manually-updating-your-DNSCrypt-server)...
During an update we copy/save the keys from the existing container, remove the short-term keys and copy them later back to the new container. Is it necessary? Isn't it possible and easier (less steps for the administrator) that the new container is re-using the existing volume (with the existing keys) of the old container?

**Comment by jedisct1** [comment]
Backing up the keys before an update is always a good idea :)

But yes, absolutely, it would be easier to reuse the existing volume.

**Comment by mibere** [comment]
I guess the command

```
docker run --ulimit nofile=90000:90000 --name=dnscrypt-server-new -p 443:443/udp -p 443:443/tcp --net=host jedisct1/dnscrypt-server init -N $SERVER -E $SERVER_IP:443
```
in step 4 has to be extended with `--volumes-from <old container>`

```
docker run --volumes-from dnscrypt-server --ulimit nofile=90000:90000 --name=dnscrypt-server-new -p 443:443/udp -p 443:443/tcp --net=host jedisct1/dnscrypt-server init -N $SERVER -E $SERVER_IP:443
```
Then the following three lines in step 5 should be unnecessary
```
docker exec dnscrypt-server-new rm -rf /opt/dnscrypt-wrapper/etc/keys/short-term
docker cp ~/keys/. dnscrypt-server-new:/opt/dnscrypt-wrapper/etc/keys
docker restart dnscrypt-server-new
```

To all the Docker experts out there, is the above correct?

2 questions:

1. Is [line 83](https://github.com/jedisct1/dnscrypt-server-docker/blob/master/Dockerfile#L83) a problem then?
2. has the "init" parameter to be omitted (as there is no need to create new keys)?

```
docker run --volumes-from dnscrypt-server --ulimit nofile=90000:90000 --name=dnscrypt-server-new -p 443:443/udp -p 443:443/tcp --net=host jedisct1/dnscrypt-server -N $SERVER -E $SERVER_IP:443
```

**Comment by ianbashford** [comment]
what about creating a dedicated volume from the beginning to keep the keys?  e.g. 

```
# docker volume create dnscrypt-keys 
# docker run --ulimit nofile=90000:90000 \
   --name=dnscrypt-server \
  -v dnscrypt-keys:/opt/dnscrypt-wrapper/etc/keys \  
   -p 443:443/udp -p 443:443/tcp \
    --net=host jedisct1/dnscrypt-server \ 
   init -N example.com -E X.X.X.X:443
```

It should be easy enough to migrate over...  I could have a go at a script for that if you like the idea.  
I believe multiple containers can all use the same volume which might also aid (manual) upgrades

**Comment by mibere** [comment]
That would be an idea too, thanks.

Has [line 83](https://github.com/jedisct1/dnscrypt-server-docker/blob/master/Dockerfile#L83) in the Dockerfile to be removed then?

**Comment by ianbashford** [comment]
I believe it would be removed yes, and replaced by the explicitly named volume.
I think something like this would migrate people -- it simplifies the upgrade quite a bit too:
```

docker volume create dnscrypt-keys
docker pull alpine
docker run --name alpine --rm -v dnscrypt-keys:/opt/dnscrypt-wrapper/etc/keys alpine /bin/sh

# in another window, copy in your saved 'keys' directory
docker cp keys alpine:/opt/dnscrypt-wrapper/etc/

# then close the alpine window.  To be tidy we'll get rid of the alpine image
docker rmi alpine:latest

# Perform the upgrade 
docker pull jedisct1/dnscrypt-server

docker stop dnscrypt-server 
docker run -d --ulimit nofile=90000:90000 -v dnscrypt-keys:/opt/dnscrypt-wrapper/etc/keys --name=dnscrypt-server-new -p 443:443/udp -p 443:443/tcp --net=host jedisct1/dnscrypt-server start

# Then you're existing tidyup -- it can be renamed when appropriate
docker update --restart=unless-stopped dnscrypt-server-new
docker volume prune
```

Let me know if you have issues with any of that...

**Comment by ianbashford** [comment]
2 things.   I'm not sure how to make the updates to this method automatically happen for people.  I'll put my mind to that.
Also, that prune command will delete our carefully constructed volume if no container's using it, so there should probably be some careful language for people around that.

**Comment by ianbashford** [comment]
Is this still of interest?   I've been running with this for a while using this set of commands on a new server
```
docker volume create dnscrypt-keys
docker pull jedisct1/dnscrypt-server
docker run --ulimit nofile=90000:90000 -v dnscrypt-keys:/opt/dnscrypt-wrapper/etc/keys --name=dnscrypt-server -p 443:443/udp -p 443:443/tcp --net=host jedisct1/dnscrypt-server init -N <NAME> -E <IP>
docker run -d --ulimit nofile=90000:90000 -v dnscrypt-keys:/opt/dnscrypt-wrapper/etc/keys --name=dnscrypt-server -p 443:443/udp -p 443:443/tcp --net=host jedisct1/dnscrypt-server start
docker update --restart=unless-stopped dnscrypt-server
docker run -d --name watchtower -v /var/run/docker.sock:/var/run/docker.sock v2tec/watchtower dnscrypt-server
docker update --restart=unless-stopped watchtower
```
The migration steps I put above work, but they'd have to be done manually.  
What do you think?

**Comment by jedisct1** [comment]
Closing as this is the case now :)
