### ISSUE TITLE
Is uninstall of BUILD_DEPS working correctly?

### ISSUE THREAD

**Issue by mibere** [jedisct1/dnscrypt-server-docker#25]
Can it be that the command

```
RUN set -x && \
    echo apk del --purge $BUILD_DEPS && \
    echo rm -rf /tmp/* /var/tmp/* /usr/local/include
```

in the Dockerfile isn't executed correctly or as expected?

All listed packages (_$BUILD_DEPS_) are still installed in the container after starting it.

**Comment by mibere** [comment]
Maybe this behavior is "by design". Found this comment

> Your commands to remove packages and clean up cache are in new layers. You cannot remove stuff from previous layers already committed (this is a fundamental Docker thing). Remove the packages and clean up the command in the same layer by adding on to the compound command:

Every _RUN_ seems to be a new layer, and therefore "apk del..." doesn't work.

**Comment by poentodewo** [comment]
Inded I can check git version
