### ISSUE TITLE
New server

### ISSUE THREAD

**Issue by ooonea** [jedisct1/dnscrypt-server-docker#29]
New server maintained by lucenera:
name: 'caris'
Stamp for dnscrypt-proxy 2.x:
   sdns: // AQcAAAAAAAAAETUxLjE1LjEwNi4xNzY6NDQzIHoBq-npX9jLHUm1YOumKcmBtXIPQSxVHB8ngzhYAgIRHjIuZG5zY3J5cHQtY2VydC5hbXMuY2hhcmlzLmNvbQ
Please add it to the list of public servers.

**Comment by jedisct1** [comment]
Is it `caris` or `charis`?

**Comment by ooonea** [comment]
charis

**Comment by jedisct1** [comment]
Welcome to Charis!
