### ISSUE TITLE
Change of servers

### ISSUE THREAD

**Issue by ooonea** [jedisct1/dnscrypt-server-docker#30]
Hi, I realize I've changed things a lot already. I have experienced. I realized that the service to which I relied was not what I was looking for. The servers that I kept were really of poor quality, above all they had only 1 GB of RAM and often netdata gave me back a warning of excessive use of the swap. Then I switched to Scaleway from which I started, which at a highly competitive price offers decent servers that do the job very well. There are no longer 'edociccio', 'kenshiro', 'denise', 'lucenera'.
'Charis' that you just added and 'suami' have remained active.
'suami' is now hosted in France and has a new stamp:
sdns: // AQcAAAAAAAAAETUxLjE1OC4xMDYuNDI6NDQzIF_Fc4XhzA13UNWqYsy2Uc5kQPn_oJ_N0lfFPVHeicOrHDIuZG5zY3J5cHQtY2VydC5mci5zdWFtaS5jb20
Thank you for your infinite patience. I hope these two servers will remain active and unchanged for as long as possible.
Long live the DNSCrypt protocol!

**Comment by jedisct1** [comment]
No problem! The list has been updated.
