### ISSUE TITLE
charis server

### ISSUE THREAD

**Issue by ooonea** [jedisct1/dnscrypt-server-docker#31]
This is new string for charis:
sdns://AQcAAAAAAAAAEzE2My4xNzIuMTY5LjE5Mjo0NDMgkS2BMokRHYm5_PjDZOxk1956VHBkRFMez6BqG7gIVhQaMi5kbnNjcnlwdC1jZXJ0LmZyLmVkby5jb20
As suami, it is hosted in France with the Scaleway service on a bare-metal server. I always used your docker. Scaleway had problems all day starting instances from Amsterdam and then I duplicated the French one. Good job.

**Comment by jedisct1** [comment]
Thank you!

**Comment by jedisct1** [comment]
I've always been wondering where all the cool names you assign to your resolvers come from? Just curious :)

**Comment by jedisct1** [comment]
The stamp and description have been updated, by the way. Thanks!

**Comment by ooonea** [comment]
Love for language, languages and those that give birth to my ideas. Indo-European languages. Like Sanskrit and Greek.

**Comment by ooonea** [comment]
Instead, I wonder, why doesn't your container point to OpenNIC? It is a very fascinating project. What do you think about it?

**Comment by jedisct1** [comment]
OpenNIC is a great project, but they still don't support DNSSEC :(

**Comment by ooonea** [comment]
Now I understand your choice. Thanks a lot. You are a very kind person.
