### ISSUE TITLE
charis server

### ISSUE THREAD

**Issue by ooonea** [jedisct1/dnscrypt-server-docker#32]
Hi,
I did my best to keep the charis server alive. But Scaleway has problems both with the deployment of the instances and with the network, both in France and in Amsterdam. I tried to create the instance several times, even of different types. But when I create it, there is no network connection, although everything is perfectly configured.
I ask you to remove charis from the list. I will only remain suami. I think it's fate.
Thanks for everything.
My best regards.

**Comment by jedisct1** [comment]
:(

Do you mean that you can't even connect to these instances?

On one of my resolvers, I had to turn off the firewall because it was enabled by default and accumulated too many states.

**Comment by ooonea** [comment]
The firewall is certainly set. Disabling it completely does not seem to me to be the case. However on suami I have the exact same configuration and everything goes regularly. Leave the issue open, I'll give it a try. But it's been a while since I've played this trick. Run for a few hours or a day and then stop working. That's why you found him off. Then on Amsterdam I just can't start a bare metal server in any way. I create the instance and it doesn't start for minutes, up to an hour. And then the server is automatically archived. I do not use the assistance, because not having a dedicated assistance plan, they take a lot to respond to requests.

**Comment by ooonea** [comment]
[edo.txt](https://github.com/jedisct1/dnscrypt-server-docker/files/3154640/edo.txt)
[suami.txt](https://github.com/jedisct1/dnscrypt-server-docker/files/3154641/suami.txt)

Migrated back to the Italian service. I'm a perfectionist obsessed, because in the end I use these servers myself and one thing must be done just fine. suami is in Italy and charis in Germany. Unfortunately the service I use now and I used does not offer bare-metal at a good price, but I chose a VPS powerful enough to no longer have the problems I had in the past. Everything is perfectly configured with an active firewall. Scaleway continued to have problems even later and the suami application also had large latency. On the hour servers the latency for me has at least dropped by 15 ms.
All my respect.

**Comment by jedisct1** [comment]
No problem, lucenera.

Which one is in Italy? Is it charis or edo? Or did you rename charis to edo?

**Comment by ooonea** [comment]
Sorry, edo is charis.
charis = Germany
suami = Italy

**Comment by jedisct1** [comment]
Updated!
