### ISSUE TITLE
[New Server] encrypt.town

### ISSUE THREAD

**Issue by EncryptTown** [jedisct1/dnscrypt-server-docker#33]
Hello @jedisct1

Let me start off by thanking you for creating dnscrypt.
And for all the hard work you put into it.
It is greatly appreciated.

I started my own server to support dnscrypt. I hope you like it.
Here is the address:

```
[static.'encrypt.town']
stamp = 'sdns://AQcAAAAAAAAAETEzLjUyLjEzOC4yMTc6ODg4IBBFTcFTuQTe-sR5uokPA7FcM00RRnHKBZylyElKcwT2HDIuZG5zY3J5cHQtY2VydC5lbmNyeXB0LnRvd24'
```

Location: Northern California, USA
DNSSEC: Enabled
Logging: No
Filters: No
Website: [encrypt.town](https://encrypt.town)

Thank you again!

**Comment by EncryptTown** [comment]
Website is temporarily down, but the dnscrypt server is running :)

**Comment by jedisct1** [comment]
...and you're in!

Welcome to Encrypt Town, and thanks a lot for running this resolver!

**Comment by EncryptTown** [comment]
Thank you so much @jedisct1 :smiley: :smiley: :smiley:
