### ISSUE TITLE
sbin/start_runit missing.

### ISSUE THREAD

**Issue by Haraade** [jedisct1/dnscrypt-server-docker#34]
Output after start of the container:

Congratulations! The container has been properly initialized.
Take a look up above at the way dnscrypt-proxy has to be configured in order
to connect to your resolver. Then, start the container with the default command.
Starting DNSCrypt service for provider:
2.dnscrypt-cert.dnscrypt-local.com
/entrypoint.sh: line 86: /sbin/start_runit: No such file or directory

**Comment by jedisct1** [comment]
Has this been solved?

**Comment by Haraade** [comment]
Yes. My mistake. Running the container on arm32v7.
