### ISSUE TITLE
Is it possible to setup a DNSCrypt Server which forwards all requests to OpenDNS?

### ISSUE THREAD

**Issue by lolcocks123** [jedisct1/dnscrypt-server-docker#37]
Hello,

Kind of a newbie here.

I currently have a forwarding DNS server running using BIND9, which forwards all requests to OpenDNS.

I was wondering if the same would be possible when settings up an DNSCrypt server.

**Comment by jedisct1** [comment]
Hi!

The easiest way is to directly install [encrypted DNS server](https://github.com/jedisct1/encrypted-dns-server). And in the configuration file, set `upstream_addr` to the server you want to use.
