### ISSUE TITLE
Migrating from physical server to Docker

### ISSUE THREAD

**Issue by modem7** [jedisct1/dnscrypt-server-docker#43]
Heya, 

I'm looking to migrate from a pi to docker for easier disaster recovery in future. 

With the docker image, I can't see anywhere where I can set my own local servers or migrate my dnscrypt-proxy.toml at all. 

Would I be able to do something akin to:

    -e DNSCRYPT_SERVER_NAMES="['scaleway-fr','google','yandex','cloudflare']" \
    -v /path/to/config/dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml \

Ultimately it'll be an upstream for pihole (also being migrated to docker).

I might be being a muppet!

Thanks!

**Comment by jedisct1** [comment]
I think this is what you are looking for: https://github.com/fekle/dnscrypt-proxy-docker

**Comment by modem7** [comment]
Thank you! That certainly looks perfect for my needs!
