### ISSUE TITLE
Remove runit dependency

### ISSUE THREAD

**Issue by taoeffect** [jedisct1/dnscrypt-server-docker#6]
Makes sense to do along with #4 and base this on the official alpine image.

If it helps you close this issue, I can grant you access to my private repo where I have these changes made. Just [let me know](https://keybase.io/greg).

My Dockerfile contains only these dependencies:

```
ENV BUILD_DEPS   build-base autoconf libevent-dev
ENV RUNTIME_DEPS libevent findutils
```

That's in addition to `ca-certificates wget` and `libressl` that come with my custom alpine base image.

**Comment by taoeffect** [comment]
To be clear, my fork handles periodic key rotation via Alpine's built-in cron daemon, removing the need for runit.

**Comment by jedisct1** [comment]
Runit is very useful, if only to restart jobs, see their status, avoid multiple identical jobs running simultaneously...
It's also a very tiny set of applications. So I'd rather keep it.
