### ISSUE TITLE
Unable to run image on arm64

### ISSUE THREAD

**Issue by axeII** [jedisct1/dnscrypt-server-docker#8]
Hi,
  I wasn't able to open docker image on arm64 architecture. Can't find instrunctions to build own dnsproxy server.  Could you please post @jedisct1 where can I find those instructions? 

Thank you ;)

**Comment by jedisct1** [comment]
You can build it with `docker build .`

For more information about how to add tags, run it, etc. you'd better look at a Docker tutorial as I don't remember any of these steps.
